name: Build Linux Kernel Module

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up kernel build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            kmod \
            linux-headers-$(uname -r)  # Installs headers for the GitHub Actions runner's kernel

      - name: Build the module
        run: |
          cd $GITHUB_WORKSPACE
          make

      - name: Verify the module
        run: |
          file hello.ko  # Check if it's a valid kernel module
          modinfo hello.ko  # Show module info

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hello_module
          path: hello.ko
          retention-days: 1
