name: Build Linux Kernel Module

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: linuxkit/kernel:5.15.12-ubuntu  # Prebuilt kernel + toolchain
      options: --privileged  # Required for kernel operations

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to latest checkout

      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y kmod file

      - name: Build the module
        run: |
          cd $GITHUB_WORKSPACE
          make
          file hello.ko  # Verify ELF format

      - name: Test module loading (emulated)
        run: |
          cd $GITHUB_WORKSPACE
          insmod ./hello.ko || true
          dmesg | grep -i "hello"
          rmmod hello || true
          dmesg | grep -i "goodbye"

      - name: Upload artifact
        uses: actions/upload-artifact@v4  # Updated to v4 (current latest)
        with:
          name: hello_module
          path: hello.ko
          retention-days: 1  # Reduces storage usage
